version: "3"
services:
  web:
    # 将 username/repo:tag 替换为您的名称和镜像详细信息
    image: fuyunhehe/test:hello
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    # 使可视化程序能够访问 Docker 的主机套接字文件
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      # 用于确保此服务仅在 swarm 管理节点上运行，而从不在工作节点上运行
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
